### PR TITLE
Readme edits

### PR DESCRIPTION
**Pull request by mepps**
I added markup to indicate bash commands, included an additional necessary environment variable, and edited some lines for readability and clarity based on my experience trying to set this up locally

### CODE REVIEW

**Comment by judisohn** [comment]
Thank you!!

**Comment by chrismcmahon** [comment]
Thanks! I was on vacation last week and missed this PR until just now. I am pleased that you seem to have it working.

**Comment by chrismcmahon** [comment]
I like the elaboration, I would like to see two changes: 

First, this markdown is a bit confused and it would be good to sort these onto separate lines: 

screen shot 2017-03-30 at 3 28 42 pm

Second, you are correct and SF_USERNAME and SF_PASSWORD are no longer used anywhere and are obsolete, so this can be removed completely: 

screen shot 2017-03-30 at 3 29 01 pm

Thanks very much for making this better!

**Comment by mepps** [comment]
@chrismcmahon I made some updates based on your comments.

**Pull request merged**
